version: 0.11

phases:
  install:
    runtime-versions:
      python: 3.9.6
  pre_build:
    commands:
      - python3.9.6 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy